import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateWellnessReport = (report) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129);
  doc.text("ManaSetu AI Wellness Report", 14, 20);

  // Subtitle
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(
    "Personalized Mental Wellness Report",
    14,
    28
  );

  // Student Information
  autoTable(doc, {
    startY: 36,
    head: [["Student Information", ""]],
    body: [
      ["Name", report.student],
      ["Email", report.email],
      ["Generated On", report.date],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [16, 185, 129],
    },
  });

  // Wellness Summary
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Wellness Summary", ""]],
    body: [
      ["Current Mood", report.mood],
      ["Wellness Score", `${report.score}/100`],
      ["Current Streak", `${report.streak} Days`],
      ["Journal Entries", report.journals],
      ["Burnout Risk", report.risk],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [34, 197, 94],
    },
  });
    // AI Insights
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["AI Insights"]],
    body: report.insights.map((insight) => [insight]),
    theme: "striped",
    headStyles: {
      fillColor: [59, 130, 246],
    },
  });

  // Recommendations
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Personalized Recommendations"]],
    body: report.recommendations.map((item) => [`✓ ${item}`]),
    theme: "striped",
    headStyles: {
      fillColor: [16, 185, 129],
    },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(16, 185, 129);
  doc.line(14, pageHeight - 25, 196, pageHeight - 25);

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by ManaSetu AI Wellness Platform",
    14,
    pageHeight - 16
  );

  doc.text(
    `Generated on ${report.date}`,
    14,
    pageHeight - 10
  );

  doc.text(
    "https://manasetu.ai",
    145,
    pageHeight - 10
  );

  // Save PDF
  doc.save("ManaSetu-Wellness-Report.pdf");
};